### ISSUE TITLE
when_any  when_all 代码有错误

### ISSUE THREAD

**Issue by sxstd001** [Codesire-Deng/co_context#109]
```cpp
    spawn_all(std::index_sequence_for<task_types...>{});
    co_await lazy::forget();  // std::suspend_always;
```
  co_await lazy::forget();   基于这个挂起肯定是错误的,  spawn_all可能立即恢复, 恢复一个没有挂起的协程.

**Comment by Codesire-Deng** [comment]
你好，感谢你阅读了源码。此处 `spawn_all` 生成的协程其实是惰性执行的，在 `co_await lazy::forget()` 执行之后，新生成的协程才有机会被调度，所以我想不存在恢复了一个没有挂起的协程的情况。

**Comment by sxstd001** [comment]
> 你好，感谢你阅读了源码。此处 `spawn_all` 生成的协程其实是惰性执行的，在 `co_await lazy::forget()` 执行之后，新生成的协程才有机会被调度，所以我想不存在恢复了一个没有挂起的协程的情况。
不清楚这是单线程还是多线程的, 若是单线程没有问题. 多线程争抢任务的话, 内核切换线程就会出现问题.

**Comment by Codesire-Deng** [comment]
`when_any`/`when_all` 的发起是单线程的，但用户的 task 可以自由切换线程，所以结束时可能是多线程的，所以这里做了内存同步(is_thread_safe 相关)。
