### ISSUE TITLE
关于本地编译使用的咨询

### ISSUE THREAD

**Issue by ChunelFeng** [Codesire-Deng/co_context#11]
大佬，您好。从b站看到您的视频介绍，找到这里，想学习使用一下。

了解到这个工程 需要依赖 mimalloc v2.0以上  `find_package(mimalloc 2.0 REQUIRED)`。
我在自己本地的 mac-m1笔记本上，通过 brew install mimalloc 无法安装 v2或以上的版本

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/37905059/181793756-2fd4a797-4016-42fd-aed5-5b5e31336068.png">

能否提供一些一下关于这方面的支持，比如将mimalloc降低到v1.7.6-stable，或者其他快速引入 mimalloc的方式，

以便我们快速在本地，跑起来 example里的内容。感谢

**Comment by tchaikov** [comment]
io uring 是 Linux 的特性，MacOS 上对应的是是 kqueue/kevent。目前 co_context 只支持 io uring。就算你能安装 mimalloc，也是无法使用的 co_context 的。

**Comment by Codesire-Deng** [comment]
> 能否提供一些一下关于这方面的支持，比如将mimalloc降低到v1.7.6-stable，或者其他快速引入 mimalloc的方式

周末会做一个`no_mimalloc`分支，让无 mimalloc 或者 1.x 版本的用户也能编译。`no_mimalloc`的其余内容会与`main`一致。

至于 OS 的问题，如 @tchaikov 所说，暂时没有办法兼容 Linux 以外的 OS，抱歉

**Comment by ChunelFeng** [comment]
大佬，感谢您的回复，了解了。

既然这个库，暂时支持Linux，是否可以考虑提供一个docker环境，和对应的使用介绍，
便于小白上手和使用。

期待这个repo的不断优化和完善。

**Comment by Codesire-Deng** [comment]
感谢支持！`no_mimalloc`分支已经上传。 关于 docker 的建议会考虑的，需要一点时间学习和考虑，谢谢建议。
