### ISSUE TITLE
rhel9 编译错误

### ISSUE THREAD

**Issue by gooker** [Codesire-Deng/co_context#31]
![image](https://user-images.githubusercontent.com/5688076/196845030-7801ec3d-d237-4988-92ce-b0450d4b3ff5.png)

[root@localhost co_context]# make
[  1%] Building CXX object lib/co_context/CMakeFiles/co_context.dir/co/condition_variable.cpp.o
[  2%] Building CXX object lib/co_context/CMakeFiles/co_context.dir/co/mutex.cpp.o
[  3%] Building CXX object lib/co_context/CMakeFiles/co_context.dir/co/semaphore.cpp.o
[  5%] Building CXX object lib/co_context/CMakeFiles/co_context.dir/io_context.cpp.o
[  6%] Building CXX object lib/co_context/CMakeFiles/co_context.dir/net/inet_address.cpp.o
[  7%] Building CXX object lib/co_context/CMakeFiles/co_context.dir/net/socket.cpp.o
In file included from /mnt/hgfs/github/co_context/include/co_context/net/socket.hpp:3,
                 from /mnt/hgfs/github/co_context/lib/co_context/net/socket.cpp:1:
/mnt/hgfs/github/co_context/include/co_context/lazy_io.hpp:469:65: error: ‘lazy_msg_ring’ in namespace ‘co_context::detail’ does not name a type
  469 |     [[nodiscard("Did you forget to co_await?")]] inline detail::lazy_msg_ring
      |                                                                 ^~~~~~~~~~~~~
make[2]: *** [lib/co_context/CMakeFiles/co_context.dir/build.make:146: lib/co_context/CMakeFiles/co_context.dir/net/socket.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:215: lib/co_context/CMakeFiles/co_context.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
[root@localhost co_context]# 
[root@localhost co_context]# uname -a
Linux localhost.localdomain 5.14.0-70.17.1.el9_0.x86_64 #1 SMP PREEMPT Wed Jul 13 18:23:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost co_context]# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-host-pie --enable-host-bind-now --enable-languages=c,c++,fortran,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.rockylinux.org/ --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --without-isl --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_64=x86-64-v2 --with-arch_32=x86-64 --build=x86_64-redhat-linux --with-build-config=bootstrap-lto --enable-link-serialization=1
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.2.1 20220127 (Red Hat 11.2.1-9) (GCC)

**Comment by Codesire-Deng** [comment]
错误已被定位且[修复](https://github.com/Codesire-Deng/co_context/commit/cc98d1e9b393df0744baf81a64bbf74123c6ac6e)！ 问题的原因是漏了一个内核版本检测。 非常感谢你的反馈！💯

**Comment by gooker** [comment]
还有失败

[root@localhost co_context]# make
[  1%] Building CXX object lib/co_context/CMakeFiles/co_context.dir/co/condition_variable.cpp.o
[  2%] Building CXX object lib/co_context/CMakeFiles/co_context.dir/co/mutex.cpp.o
[  3%] Building CXX object lib/co_context/CMakeFiles/co_context.dir/co/semaphore.cpp.o
[  5%] Building CXX object lib/co_context/CMakeFiles/co_context.dir/io_context.cpp.o
[  6%] Building CXX object lib/co_context/CMakeFiles/co_context.dir/net/inet_address.cpp.o
[  7%] Building CXX object lib/co_context/CMakeFiles/co_context.dir/net/socket.cpp.o
[  7%] Built target co_context
[  9%] Building CXX object test/CMakeFiles/rand4kw_callback.dir/rand4kw_callback.cpp.o
[ 10%] Linking CXX executable rand4kw_callback
[ 10%] Built target rand4kw_callback
[ 11%] Building CXX object test/CMakeFiles/rand4kr_multithread_blocking.dir/rand4kr_multithread_blocking.cpp.o
[ 13%] Linking CXX executable rand4kr_multithread_blocking
[ 13%] Built target rand4kr_multithread_blocking
[ 14%] Building CXX object test/CMakeFiles/rand4kr_forloop.dir/rand4kr_forloop.cpp.o
[ 15%] Linking CXX executable rand4kr_forloop
[ 15%] Built target rand4kr_forloop
[ 17%] Building CXX object test/CMakeFiles/rand4kr_callback.dir/rand4kr_callback.cpp.o
[ 18%] Linking CXX executable rand4kr_callback
[ 18%] Built target rand4kr_callback
[ 19%] Building CXX object test/CMakeFiles/rand4kr.dir/rand4kr.cpp.o
[ 21%] Linking CXX executable rand4kr
[ 21%] Built target rand4kr
[ 22%] Building CXX object test/CMakeFiles/photon_streaming_client.dir/photon_streaming_client.cpp.o
[ 23%] Linking CXX executable photon_streaming_client
[ 23%] Built target photon_streaming_client
[ 25%] Building CXX object test/CMakeFiles/cat.dir/cat.cpp.o
[ 26%] Linking CXX executable cat
[ 26%] Built target cat
[ 27%] Building CXX object test/CMakeFiles/fingerprint.dir/fingerprint.cpp.o
[ 28%] Linking CXX executable fingerprint
[ 28%] Built target fingerprint
[ 30%] Building CXX object test/CMakeFiles/swtch.dir/swtch.cpp.o
[ 31%] Linking CXX executable swtch
[ 31%] Built target swtch
[ 32%] Building CXX object test/CMakeFiles/channel.dir/channel.cpp.o
[ 34%] Linking CXX executable channel
[ 34%] Built target channel
[ 35%] Building CXX object test/CMakeFiles/ctx_swtch.dir/ctx_swtch.cpp.o
[ 36%] Linking CXX executable ctx_swtch
[ 36%] Built target ctx_swtch
[ 38%] Building CXX object test/CMakeFiles/rand4kr_blocking.dir/rand4kr_blocking.cpp.o
[ 39%] Linking CXX executable rand4kr_blocking
[ 39%] Built target rand4kr_blocking
[ 40%] Building CXX object test/CMakeFiles/fingerprint_blocking.dir/fingerprint_blocking.cpp.o
[ 42%] Linking CXX executable fingerprint_blocking
[ 42%] Built target fingerprint_blocking
[ 43%] Building CXX object test/CMakeFiles/fingerprint_client.dir/fingerprint_client.cpp.o
[ 44%] Linking CXX executable fingerprint_client
[ 44%] Built target fingerprint_client
[ 46%] Building CXX object test/CMakeFiles/photon_pingpong_client.dir/photon_pingpong_client.cpp.o
[ 47%] Linking CXX executable photon_pingpong_client
[ 47%] Built target photon_pingpong_client
[ 48%] Building CXX object test/CMakeFiles/coro_lifetime.dir/coro_lifetime.cpp.o
[ 50%] Linking CXX executable coro_lifetime
[ 50%] Built target coro_lifetime
[ 51%] Building CXX object test/CMakeFiles/nc_uring.dir/nc_uring.cpp.o
[ 52%] Linking CXX executable nc_uring
[ 52%] Built target nc_uring
[ 53%] Building CXX object test/CMakeFiles/generator_test.dir/generator_test.cpp.o
/mnt/hgfs/github/co_context/test/generator_test.cpp: In function ‘co_context::generator<long unsigned int, long unsigned int> {anonymous}::nested_sequences_example()’:
/mnt/hgfs/github/co_context/test/generator_test.cpp:55:53: error: class template argument deduction failed:
   55 |     co_yield co_context::ranges::elements_of{fib(10)};
      |                                                     ^
/mnt/hgfs/github/co_context/test/generator_test.cpp:55:53: error: no matching function for call to ‘elements_of(co_context::generator<long unsigned int>)’
In file included from /mnt/hgfs/github/co_context/test/generator_test.cpp:1:
/mnt/hgfs/github/co_context/include/co_context/generator.hpp:252:12: note: candidate: ‘template<class _Rng, class _Alloc> elements_of()-> co_context::ranges::elements_of<_Rng, _Alloc>’
  252 |     struct elements_of {
      |            ^~~~~~~~~~~
/mnt/hgfs/github/co_context/include/co_context/generator.hpp:252:12: note:   template argument deduction/substitution failed:
/mnt/hgfs/github/co_context/test/generator_test.cpp:55:53: note:   candidate expects 0 arguments, 1 provided
   55 |     co_yield co_context::ranges::elements_of{fib(10)};
      |                                                     ^
In file included from /mnt/hgfs/github/co_context/test/generator_test.cpp:1:
/mnt/hgfs/github/co_context/include/co_context/generator.hpp:252:12: note: candidate: ‘template<class _Rng, class _Alloc> elements_of(co_context::ranges::elements_of<_Rng, _Alloc>)-> co_context::ranges::elements_of<_Rng, _Alloc>’
  252 |     struct elements_of {
      |            ^~~~~~~~~~~
/mnt/hgfs/github/co_context/include/co_context/generator.hpp:252:12: note:   template argument deduction/substitution failed:
/mnt/hgfs/github/co_context/test/generator_test.cpp:55:53: note:   ‘co_context::generator<long unsigned int>’ is not derived from ‘co_context::ranges::elements_of<_Rng, _Alloc>’
   55 |     co_yield co_context::ranges::elements_of{fib(10)};
      |                                                     ^
In file included from /mnt/hgfs/github/co_context/test/generator_test.cpp:1:
/mnt/hgfs/github/co_context/include/co_context/generator.hpp:258:5: note: candidate: ‘template<class _Rng, class _Alloc> co_context::ranges::elements_of(_Rng&&, _Alloc)-> co_context::ranges::elements_of<_Rng&&, _Alloc>’
  258 |     elements_of(_Rng &&, _Alloc = {}) -> elements_of<_Rng &&, _Alloc>;
      |     ^~~~~~~~~~~
/mnt/hgfs/github/co_context/include/co_context/generator.hpp:258:5: note:   template argument deduction/substitution failed:
/mnt/hgfs/github/co_context/include/co_context/generator.hpp: In substitution of ‘template<class _Rng, class _Alloc> co_context::ranges::elements_of(_Rng&&, _Alloc)-> co_context::ranges::elements_of<_Rng&&, _Alloc> [with _Rng = co_context::generator<long unsigned int>; _Alloc = std::allocator<std::byte>]’:
/mnt/hgfs/github/co_context/test/generator_test.cpp:55:53:   required from here
/mnt/hgfs/github/co_context/include/co_context/generator.hpp:258:5: error: template constraint failure for ‘template<class _Rng, class _Alloc>  requires  range<_Rng> struct co_context::ranges::elements_of’
/mnt/hgfs/github/co_context/include/co_context/generator.hpp:258:5: note: constraints not satisfied

**Comment by Codesire-Deng** [comment]
相信与编译器的版本兼容性有关。我们暂时禁用了`generator_text`的编译，并会尝试用 gcc11.2 复现这个问题并修复之。再次感谢反馈！

**Comment by tchaikov** [comment]
你可能需要用 gcc-toolset-12 中的 g++ 编译器来编译。clang-14 也会出错。具体原因是比较老的 clang 不支持 https://wg21.link/p1091r3 和 https://wg21.link/p1381r1，因此不允许 capture structured binding。

**Comment by tchaikov** [comment]
> 相信与编译器的版本兼容性有关。我们暂时禁用了`generator_test`的编译，并会尝试用 gcc11.2 复现这个问题并修复之。再次感谢反馈！

我认为老版本 gcc (< 12) 或者 clang (<14) 对 coroutines 的支持都不够好，而且维护者也缺乏动力 backport master 上的 fix。bugzilla 上就有一些 issue 是 gcc 的，clang 也有。另外 libstdc++ 对 range 支持目前也不够好。所以还是建议开发者用最新的 gcc 和 clang 更好一些。这样能避免一些莫名其妙的坑。

**Comment by Codesire-Deng** [comment]
@gooker 知乎私信失败了，所以不能回复你

**Comment by gooker** [comment]
看起来gcc11对coroutines 支持还是有问题,之前有个库也看到这个说法,我得看看rhel9 (rockylinux9)有没有提供12版本,暂时没能力自己升级.
@Codesire-Deng  ok.

> > 相信与编译器的版本兼容性有关。我们暂时禁用了`generator_test`的编译，并会尝试用 gcc11.2 复现这个问题并修复之。再次感谢反馈！
> 
> 我认为老版本 gcc (< 12) 或者 clang (<14) 对 coroutines 的支持都不够好，而且维护者也缺乏动力 backport master 上的 fix。bugzilla 上就有一些 issue 是 gcc 关于 coroutines 的，clang 也有。另外 libstdc++ 对 range 支持目前也不够好。所以还是建议开发者用最新的 gcc 和 clang 更好一些。这样能避免一些莫名其妙的坑。

**Comment by Codesire-Deng** [comment]
看来std::range在gcc12也经历了更改。我上传了`no_generator`分支，剔除了有关代码，这不会影响主要功能，可能可以在gcc11下通过编译。Anyway, 抱歉打扰您了！ @gooker 

```bash
$ git fetch origin no_generator
$ git switch no_generator
$ cmake -B build; cmake --build build -j
$ build/example/timer # 运行任意example
```

**Comment by Codesire-Deng** [comment]
> @Codesire-Deng rt 11.2是 rhel9/rocky9 自带,暂时没找到devtoolset-12-toolchain,自己编12有难度..

顺带一提，我用包管理器安装的 gcc 11.3.0 是可以完整编译的，还没弄懂哪里出现了问题🤣

**Comment by tchaikov** [comment]
> @Codesire-Deng rt 11.2是 rhel9/rocky9 自带,暂时没找到devtoolset-12-toolchain,自己编12有难度..
> ![image](https://user-images.githubusercontent.com/5688076/196917700-d800b03f-8dec-4199-9f9c-17c6555dc915.png)

https://centos.pkgs.org/9-stream/centos-appstream-x86_64/gcc-toolset-12-12.0-5.el9.x86_64.rpm.html 

所以你得 enable appstream 才行。这是我机器 (rockylinux 9) 上的输出：

```console
$ dnf repolist enabled
repo id                                                                                                        repo name
appstream                                                                                                      Rocky Linux 9 - AppStream
baseos                                                                                                         Rocky Linux 9 - BaseOS
crb                                                                                                            Rocky Linux 9 - CRB
elrepo                                                                                                         ELRepo.org Community Enterprise Linux Repository - el9
elrepo-kernel                                                                                                  ELRepo.org Community Enterprise Linux Kernel Repository - el9
epel                                                                                                           Extra Packages for Enterprise Linux 9 - x86_64
extras                                                                                                         Rocky Linux 9 - Extras
```

如果你的输出里面没有 appstream，就需要 enable 之：
```console
$ sudo dnf config-manager --set-enabled appstream
```

**Comment by tchaikov** [comment]
@gooker dts 是以前的名字，现在叫 GTS。

**Comment by gooker** [comment]
> @gooker dts 是以前的名字，现在叫 GTS。

感谢,学到了

**Comment by tchaikov** [comment]
@Codesire-Deng @gooker 我们在 CMake 里面硬性要求 clang-14+ 或者 gcc-12+ 如何？

**Comment by Codesire-Deng** [comment]
> @Codesire-Deng @gooker 我们在 CMake 里面硬性要求 clang-14+ 或者 gcc-12+ 如何？

一周时间我研究一下吧😃

**Comment by tchaikov** [comment]
另外的做法就是直接在 CMake 里面写上需要的各种能力，见 https://cmake.org/cmake/help/latest/manual/cmake-compile-features.7.html#compile-feature-requirements 和 https://cmake.org/cmake/help/latest/prop_gbl/CMAKE_CXX_KNOWN_FEATURES.html。
如果用到 CMake 没有包含的 feature，就需要在配置阶段，尝试编译会出问题的代码，测试编译器和标准库的能力。

这个方法虽然更正规，但是难免挂一漏万。所以直接测试编译器版本简单粗暴，好处是比较简单。

**Comment by Codesire-Deng** [comment]
已经在文档和 `CMakeLists.txt` 中要求 GCC 11.3 以上或者 Clang 14 以上。😃

在 Clang 14 中，部分 feature 不受支持，已经用宏来暂时禁用它们。
