### ISSUE TITLE
Which features require GCC compiler

### ISSUE THREAD

**Issue by GavinRay97** [Codesire-Deng/co_context#39]
Out of curiosity, why can it not compile with Clang?

**Comment by Codesire-Deng** [comment]
We found that features related to ranges like `generator` and `std::views` can not compile with Clang 14. The situation is worse when we replace libstdc++ by libc++. There are other small missing features such as `__cpp_lib_jthread` and `__cpp_lib_assume_aligned`.

Fortunately, the core features(about coroutines and io_uring) still compile with Clang. So we are going to support Clang 14 in the next version! It is on the branch [dev_loop_per_thread](https://github.com/Codesire-Deng/co_context/tree/dev_loop_per_thread) for now.

**Comment by GavinRay97** [comment]
Ah that makes sense, thank you!
