### ISSUE TITLE
你好 咨询一下调度器效率问题

### ISSUE THREAD

**Issue by hankai17** [Codesire-Deng/co_context#4]
https://github.com/Codesire-Deng/co_context/blob/4d67275232ff0ec794993f10518d9e2f420eea91/lib/co_context/io_context.cpp#L182
```
创建、运行、销毁高竞争协程的频率可达 58 M（线程数=4，swap_capacity=32768，0.986 s 内完成 58 M 原子变量自增），代码见 example/nop.cpp
```
能否认为 从协程wait 到 协程resume的最小间隔时间为(58M/0.986) = 58.8ns

**Comment by Codesire-Deng** [comment]
你好！在最近一次本地测试中，从“一个协程 wait”到“另一个协程 resume”的耗时是 37 ns，代码见于 [test/ctx_swtch.cpp](../blob/dev_submit_reorder/test/ctx_swtch.cpp)。因为 I/O 延迟通常会超过 37 ns，所以足以代表业务下的表现。至于 58.8 ns 这个结果是因为业务逻辑锁了总线，使延迟增加了，不能完全代表框架的效率。

但如果你想探究从 “一个协程 wait” 到 “这个协程 resume”的耗时，忽略调度器 pipeline，就要两次吃满跨核传输延迟，实际表现为 85 ns。

PS: 感谢提醒，原本的 example/nop.cpp 已经移动至 [test/nop.cpp](../blob/dev_submit_reorder/test/nop.cpp)，readme 将在下一次 commit 更正。
