### ISSUE TITLE
test下示例编译出错

### ISSUE THREAD

**Issue by ComixHe** [Codesire-Deng/co_context#45]
1. 对于liburingcxx::uring模板类，没有一个可以由整数构造的构造函数，导致以下代码出错：

```cpp
    liburingcxx::uring<0> ring{4};
```

2. 在rand4kr_callback.cpp中，包含了不存在的头文件"co_context/utility/buffer.hpp"
3. config::workers_number不存在

**Comment by Codesire-Deng** [comment]
是的，因为近期的大量重构，部分 test 会编译失败。我们在未来将重写多数性能测试，添加正确性测试。🤠

**Comment by ComixHe** [comment]
那请问重构对于目前main分支代码的可用性会有影响吗？也就是说现在使用库本身会出现什么问题吗？

**Comment by Codesire-Deng** [comment]
main 分支保证所有公开接口和 example 的可用性（除 test/ 目录需要重写以外）。

**Comment by ComixHe** [comment]
好的我明白了，多谢。

**Comment by ComixHe** [comment]
那如果我想直接使用libcxxuring的话，会有什么问题吗？例如我列出的第一条中没有相应的构造函数，只有一个默认构造函数，也就是说后续都期望先构造一个uring再用init来初始化这个uring？

**Comment by Codesire-Deng** [comment]
严格来讲 [liburingcxx](https://github.com/Codesire-Deng/liburingcxx) 只是 co_context 的依赖项……但是你确实可以直接使用它！😃  它尽量和 [axboe/liburing](https://github.com/axboe/liburing) 保持相似。它们的主要区别是 liburingcxx 将 `flags` 常量化了，因此要作为模板参数来用。


> 例如我列出的第一条中没有相应的构造函数，只有一个默认构造函数，也就是说后续都期望先构造一个uring再用init来初始化这个uring？

是的。因为 init 通常只运行一次，所以我们采用和原版一样的做法。

**Comment by ComixHe** [comment]
目前gcc可以顺利编译全部代码，但是在CMakeLists.txt中将编译器指定为clang时，clang编译器的前端出现了编译bug,不知道是不是我环境的问题，不过我已经向llvm提了个issus...

**Comment by ComixHe** [comment]
之前我在llvm提的那个issus需要一个最小复现，请问您有兴趣去看一下吗？

**Comment by Codesire-Deng** [comment]
好的，有空我会尝试复现一下。 在我的本地环境，Clang 16.0.0-git 没有出现这个 bug。

**Comment by ComixHe** [comment]
我的本地环境是archlinux,clang版本为14.0.6,我尝试切换到clang-git(16.0.0_r441380.97842fcba9e3a-1)依旧出现崩溃问题。

```
cmake -B build -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DBUILD_TESTS=on
-- The CXX compiler identification is Clang 16.0.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
target_kernel_version = 6.0.12-arch1-1
kernel_version_major = 6
kernel_version_patchlevel = 0
Release
Disable -fsanitize for clang
CMAKE_CXX_FLAGS =  -fsized-deallocation -std=c++20 -Wall -march=native
mimalloc 2.0 enabled
-- Configuring done
-- Generating done
-- Build files have been written to: /home/comix/workspace/co_context/build

```
