### ISSUE TITLE
build/example/timer这个样例，没有等1s到就直接输出了

### ISSUE THREAD

**Issue by linguoxuan** [Codesire-Deng/co_context#61]
我把它改成每10s输出，也是一样，一运行就不断输出，完全不会等时间timeout。

**Comment by Codesire-Deng** [comment]
Hi，请问你的 Linux 发行版和内核版本是？

我想我可以复现你的问题，谢谢！

**Comment by Codesire-Deng** [comment]
可能是 co_context 使用了太新的 io_uring 选项而内核版本尚未支持。我会在今晚上传一个补丁，解决这个问题。

**Comment by Codesire-Deng** [comment]
> > > 
> > 
> > 
> > ubuntu20.04 Linux ubun2004 5.15.0-67-generic #74~20.04.1-Ubuntu SMP Wed Feb 22 14:52:34 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
> 
> 我在另外一个服务器上试了也是同样问题：ubuntu22.04，5.15.0-58-generic

请问是包含了补丁的版本吗，补丁是在今晚 8 点发布到 main 分支上的

**Comment by linguoxuan** [comment]
> > > > 
> > > 
> > > 
> > > ubuntu20.04 Linux ubun2004 5.15.0-67-generic #74~20.04.1-Ubuntu SMP Wed Feb 22 14:52:34 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
> > 
> > 
> > 我在另外一个服务器上试了也是同样问题：ubuntu22.04，5.15.0-58-generic
> 
> 请问是包含了补丁的版本吗，补丁是在今晚 8 点发布到 main 分支上的

解决了，还有一个问题就是cmakeList.txt上设置gcc编译选项的时候要加上-pthread，否则链接出错

**Comment by Codesire-Deng** [comment]
感谢你的测试！ Cmake已经补上[线程库的链接](https://github.com/Codesire-Deng/co_context/commit/9a626c3626dade3a05ef40f2467a12863f6309d4#diff-c7f902aded813a09b733093bb51bc67ead93102348ed770b36d52ead94da3db6R8)。
