### ISSUE TITLE
co_context/include/uring/compat.h:7:10: fatal error: linux/openat2.h: No such file or directory

### ISSUE THREAD

**Issue by iKautin** [Codesire-Deng/co_context#63]
这是缺少什么库的啊?

**Comment by Codesire-Deng** [comment]
这是 Linux 自有的库，从 5.6 版本引入。您的内核版本可能老于 5.6，运行 `uname -r` 即可查看。

如果版本至少到达 5.6，可以尝试安装这个包： `linux-headers-$(uname -r)` 或者 `kernel-devel`。

**Comment by Codesire-Deng** [comment]
https://github.com/Codesire-Deng/co_context/commit/b8a218adb245ce07ec64ee62037ed5a8335edb94 兼容性更新：现在支持在没有<linux/openat2.h>的环境下编译了！
