### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tchaikov** [Codesire-Deng/co_context#7]
现在 co_context 使用的许可证是 AGPL。所以对于一般的闭源服务来说，如果链接使用 co_context，我们只能对内提供服务。有没有考虑使用更宽松的许可证，比如 MIT license，或者 apache license 2.0 呢？

**Comment by Codesire-Deng** [comment]
> _No description provided._

老哥忘记输入了？

**Comment by tchaikov** [comment]
哦，对不起。早上写进去的内容没有提交。刚才补上了。谢谢提醒。

**Comment by Codesire-Deng** [comment]
> 现在 co_context 使用的许可证是 AGPL。所以对于一般的闭源服务来说，如果链接使用 co_context，我们只能对内提供服务。有没有考虑使用更宽松的许可证，比如 MIT license，或者 apache license 2.0 呢？

感谢指导，有考虑 Apache-2.0 license，切换许可证只是时间问题。
