### ISSUE TITLE
如何实现交叉编译

### ISSUE THREAD

**Issue by wangzhankun** [Codesire-Deng/co_context#88]
我观察到`cmake/Platform.cmake`里面有检查Linux内核的代码。我现在想在riscv的内核上面跑，我的开发环境是x86,因此需要使用riscv的toolchain进行交叉编译，请问该如何实现呢？
另外，我自己编译的是linux 5.15的内核，请问在编译内核时需要特殊的编译选项吗？
开发环境内核：6.2
riscv主板内核：5.15
riscv-toolchain-gcc: 12.2.0

**Comment by Codesire-Deng** [comment]
交叉编译时，**至少需要将 `CMAKE_SYSTEM_VERSION` 定义为 `5.15`**，这样内置的 liburingcxx 才能正常工作。

除此之外，还建议：
1. 新建一个文件 `path/CrossCompile.cmake`，其中需要定义以下变量：
2. 定义 `CMAKE_SYSTEM_NAME` 为 `Linux`，令 cmake 知道你正在交叉编译；
3. 定义 `CMAKE_SYSTEM_VERSION` 为 `5.15`；
4. 定义 `CMAKE_CXX_COMPILER` 为你的 toolchain 编译器；
5. 定义 `CMAKE_SYSROOT` 为你的内核根目录；
6. 定义几个 `CMAKE_FIND_ROOT_PATH_MODE_*` 来控制 `find_XXX` 命令的查找范围；

CrossCompile.cmake 的一个例子如下：
```cmake
# CrossCompile.cmake
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_SYSTEM_VERSION 5.15)
set(CMAKE_SYSROOT /home/devel/rasp-pi-rootfs)

set(tools /home/devel/gcc-12.2-linaro-rpi-gnueabihf)
set(CMAKE_C_COMPILER ${tools}/bin/arm-linux-gnueabihf-gcc)
set(CMAKE_CXX_COMPILER ${tools}/bin/arm-linux-gnueabihf-g++)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
```

在编译你的项目时，或者单独编译 co_context 时，像这样调用 cmake：

```bash
cmake -B build . -DCMAKE_TOOLCHAIN_FILE=path/CrossCompile.cmake
cmake --build build -j
```

参考文档：[Cross Compiling](https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling)

**Comment by wangzhankun** [comment]
但是提示有错误：
```log
The target system is: Linux - 5.15 - riscv64
The host system is: Linux - 6.2.0-36-generic - x86_64
```

**Comment by wangzhankun** [comment]
riscv交叉编译记录：

`co_context/cmake/CompileOption.cmake:18` 中的 `-march=native`需要删除；
`co_context/include/co_context/detail/compat.hpp` 中关于`CO_CONTEXT_PAUSE`的定义可以修改为如下：
```c++
#if defined(__clang__) || defined(__GNUC__) || defined(__GNUG__)
#if defined(__i386__) || defined(__x86_64__)
#define CO_CONTEXT_PAUSE __builtin_ia32_pause
#elif defined(__riscv)
#define CO_CONTEXT_PAUSE() __asm__ volatile("mfence iorw, iorw")
#endif
#elif defined(_MSC_VER)
#define CO_CONTEXT_PAUSE _mm_pause
#else
#define CO_CONTEXT_PAUSE __builtin_ia32_pause
#endif
```

**Comment by wangzhankun** [comment]
在riscv下面似乎不支持`lock_free`，有什么替代方法吗？
```log
/keystone/co-server/co_context/include/co_context/detail/spsc_cursor.hpp: In instantiation of 'struct co_context::spsc_cursor<short unsigned int, 16384, co_context::unsafe>':
/keystone/co-server/co_context/include/co_context/detail/worker_meta.hpp:83:55:   required from here
/keystone/co-server/co_context/include/co_context/detail/spsc_cursor.hpp:17:35: error: static assertion failed
   17 |     static_assert(std::atomic<T>::is_always_lock_free);
      |                                   ^~~~~~~~~~~~~~~~~~~
```
我把16384调小至16也是编译不通过。

**Comment by wangzhankun** [comment]
关于`static_assert(std::atomic<uint16_t>::is_always_lock_free);`的问题，需要将riscv的编译器升级至13.2.0，https://github.com/riscv-collab/riscv-gcc/issues/15#issuecomment-1800973467

**Comment by Codesire-Deng** [comment]
非常感谢你的建议，我希望保留这个 open issue，直到上面提到的问题解决。

**Comment by Codesire-Deng** [comment]
> 关于`static_assert(std::atomic<uint16_t>::is_always_lock_free);`的问题，需要将riscv的编译器升级至13.2.0，[riscv-collab/riscv-gcc#15 (comment)](https://github.com/riscv-collab/riscv-gcc/issues/15#issuecomment-1800973467)

如果编译器不便升级，可暂时考虑修改数据类型：
https://github.com/Codesire-Deng/co_context/blob/main/include/co_context/config.hpp#L79
```c++
using cur_t = uint32_t;
```
