### ISSUE TITLE
多线程通信

### ISSUE THREAD

**Issue by wangzhankun** [Codesire-Deng/co_context#90]
# 场景描述
我在同一个进程里面设计了两个线程A和B，其中A负责加密运算，B负责处理HTTP请求。
B是使用协程实现的高并发WEB服务器，A是一个死循环，一直等待B的数据。B在最终将数据发送给客户端之前，都需要将数据发送给A线程，由A线程进行加密。由于A是计算密集型的，因此使用协程反而会导致效率下降。A线程在加密完成之后再将数据发给B线程，由B线程将数据发送给客户端。
请问在这种情况下该如何实现呢？

**Comment by zd847239** [comment]
计算密集型和 IO 密集型任务混合几乎没有性能损失，因为每个线程的 CPU 总是 100% 利用率，而且没有空转 (busy loop)。
针对你的场景，我推荐将加密和HTTP任务**安排到不同的 `io_context`**。在实现上，一个 `io_context` 对应一个线程，恰好能对应上你的 A/B 线程模型。

在 A/B `io_context` 之间用 `channel` 通信即可，这里有一个例子：[channel.cpp](https://github.com/Codesire-Deng/co_context/blob/main/example/channel.cpp)

需要提示的是，在有多个 `io_context` 的场景下，它们是不会自动结束的，这是为了防止线程间通信延迟造成信息丢失。如果实在需要 kill `io_context`，可以使用 `this_io_context().can_stop();`

**Comment by Codesire-Deng** [comment]
计算密集型和 IO 密集型任务混合几乎没有性能损失，因为每个线程的 CPU 总是 100% 利用率，而且没有空转 (busy loop)。
针对你的场景，我推荐将加密和HTTP任务**安排到不同的 `io_context`**。在实现上，一个 `io_context` 对应一个线程，恰好能对应上你的 A/B 线程模型。

在 A/B `io_context` 之间用 `channel` 通信即可，这里有一个例子：[channel.cpp](https://github.com/Codesire-Deng/co_context/blob/main/example/channel.cpp)

需要提示的是，在有多个 `io_context` 的场景下，它们是不会自动结束的，这是为了防止线程间通信延迟造成信息丢失。如果实在需要 kill `io_context`，可以使用 `this_io_context().can_stop();`

**Comment by wangzhankun** [comment]
`co_context::mutex`和`co_context::condition_variable`是线程安全的吗？如果是的话，对于同一个线程的通信是不是这种同步开销是有害的？是否可以提供一个同一线程内部的线程不安全的`co_context::condition_variable`？

**Comment by Codesire-Deng** [comment]
> `co_context::mutex`和`co_context::condition_variable`是线程安全的吗？如果是的话，对于同一个线程的通信是不是这种同步开销是有害的？

是线程安全的，有原子变量读-改-写的开销。

> 是否可以提供一个同一线程内部的线程不安全的`co_context::condition_variable`？

可以。估计在 3 天内完成草稿。

**Comment by wangzhankun** [comment]
考虑到线程调度的问题估计得用内存屏障处理。（PS：请问您的论文方便放出来吗？想系统学习一下co_context的设计。另外，关于C++20的语法您是通过什么途径学习的呀？）

**Comment by Codesire-Deng** [comment]
如果跨 `io_context` 使用同步原语，确实需要用线程安全的版本。考虑到 x86 下单线程原子指令的开销很低，默认全用线程安全的 `mutex`, `condition_variable` 的开销通常可以接受。当然在 RISC-V 的表现如何，就是另一个话题了。

*论文我找找看吧*

C++20 是看 [cppcoro](https://github.com/lewissbaker/cppcoro) 和 cppreference 硬啃的，当时资料不如现在丰富

**Comment by Codesire-Deng** [comment]
文章裁剪之后可以公开：#94 ，请留意一年半以来，功能和性能已有不少变化和改进。
