### ISSUE TITLE
在qemu下无法进行端口转发

### ISSUE THREAD

**Issue by wangzhankun** [Codesire-Deng/co_context#91]
我正确实现了我的httpd,并在x86下编译成功，使用 #88 提到的交叉编译的方法，将编译出的服务程序放到qemu模拟器中的linux下运行发现无法实现端口转发。我使用libevent实现的服务器是可以实现端口转发的。

我在服务器中同时实现了client, client可以与server进行通信，唯一的问题是，无法将服务端口转发到qemu外面。
在qemu中 同时运行client和server,成功
<img width="503" alt="image" src="https://github.com/Codesire-Deng/co_context/assets/35724924/10736b35-336c-4f52-814f-6b0104a678a9">
使用curl在qemu外连接服务器失败
<img width="359" alt="image" src="https://github.com/Codesire-Deng/co_context/assets/35724924/e41f8430-0eda-4a6b-91ab-c8b79ae2071e">

## 环境
* host: ubuntu 22.04 6.2.0-36-generic
* qemu: 6.2.94
* inux kernel for qemu-riscv64: 5.19
* riscv-toolchain gcc : 12.2.0
```sh
# riscv编译器环境
docker pull registry.cn-hangzhou.aliyuncs.com/loongenclave/riscv-basic:12.2.0
```

### qemu启动命令
```sh
qemu-system-riscv64 \
-machine virt -nographic -m 2048 -smp 4 \
-bios /usr/lib/riscv64-linux-gnu/opensbi/generic/fw_jump.bin \
-kernel /usr/lib/u-boot/qemu-riscv64_smode/uboot.elf \
-device virtio-net-device,netdev=eth0 -netdev user,id=eth0,hostfwd=tcp::2222-:22,hostfwd=tcp::8080-:8080,hostfwd=tcp::8081-:8081 \
-device virtio-rng-pci \
-drive file=ubuntu-22.04.3-preinstalled-server-riscv64+unmatched.img,format=raw,if=virtio
```

### ssh上传文件的脚本
```sh
#!/bin/bash


SSH_OPTIONS=""
USER=ubuntu
PORT=2222

upload_folder_to_qemu() {
    echo "Uploading \"$1\" folder to QEMU ..."
    scp ${SSH_OPTIONS} -P ${PORT} -r $1 ${USER}@localhost:.
}

upload_to_qemu() {
    echo "Uploading \"$(basename $1)\" to QEMU ..."
    scp ${SSH_OPTIONS} -P ${PORT} $1 ${USER}@localhost:.
}

run_in_qemu() {
    echo "Running \"$1\" in QEMU ..."
    ssh ${SSH_OPTIONS} -p ${PORT} ${USER}@localhost "$1"
}

upload_to_qemu /home/wang/Documents/keystone/co-server/build/cross/riscv64/release/coroutine
```

**Comment by wangzhankun** [comment]
可以参考这篇文章运行riscv的ubuntu：
https://wiki.ubuntu.com/RISC-V/QEMU?_ga=2.5095924.612491376.1699520142-1950424923.1698758296
用户名和密码分别为 ubuntu:ubuntu

**Comment by Codesire-Deng** [comment]
请对 `config.hpp` 尝试这个 quick fix：

```diff
-    inline constexpr bool is_loopback_only = true;
-    // inline constexpr bool is_loopback_only = false;
+    // inline constexpr bool is_loopback_only = true;
+    inline constexpr bool is_loopback_only = false;
```

https://github.com/Codesire-Deng/co_context/blob/49d86d6e0495fb2e8528879165314025701142cc/include/co_context/config.hpp#L111-L112

我暂时在忙，今天稍后会尝试复现这个问题。

**Comment by wangzhankun** [comment]
成功了，非常感谢。
